# see https://man.sr.ht/builds.sr.ht/compatibility.md#freebsd
image: freebsd/latest
packages:
- databases/sqlite3
- devel/boehm-gc-threaded
- devel/pcre
- devel/sdl20
- devel/sfml
- www/node
- devel/gmake
sources:
- https://github.com/nim-lang/Nim
environment:
  CC: /usr/bin/clang
tasks:
- setup: |
    cd Nim
    if [ "${GITHUB_PR_NUMBER+1}" ]; then
      # this was a PR, so we need to checkout devel and try to merge into it
      # see https://man.sr.ht/dispatch.sr.ht/github.md#environment-variables
      # actual values for a job can be accessed with urls like: https://builds.sr.ht/api/jobs/430827/manifest
      git remote -v
      git branch

      git pull origin devel
    fi
    git clone --depth 1 -q https://github.com/nim-lang/csources.git
    gmake -C csources -j $(sysctl -n hw.ncpu)
    bin/nim c --skipUserCfg --skipParentCfg koch
    echo 'export PATH=$HOME/Nim/bin:$PATH' >> $HOME/.buildenv
- test: |
    cd Nim
    if ! ./koch runCI; then
      nim c -r tools/ci_testresults.nim
      exit 1
    fi
triggers:
- action: email
  condition: failure
  to: Andreas Rumpf <rumpf_a@web.de>
