name: GCC 4 CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: 'debian/eol:lenny'
    timeout-minutes: 60 # refs bug #18178
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: 'Install dependencies (Linux amd64)'
        run: |
          sudo apt-fast update -qq
          DEBIAN_FRONTEND='noninteractive' \
            sudo apt-fast install --no-install-recommends -yq \
              libcurl4-openssl-dev libgc-dev libsdl1.2-dev libsfml-dev \
              valgrind libc6-dbg libblas-dev xorg-dev

      - name: 'Add build binaries to PATH'
        shell: bash
        run: echo "${{ github.workspace }}/bin" >> "${GITHUB_PATH}"

      - name: 'Build csourcesAny'
        shell: bash
        run: . ci/funs.sh && nimBuildCsourcesIfNeeded CC=gcc

      - name: 'koch, Run CI'
        shell: bash
        run: . ci/funs.sh && nimInternalBuildKochAndRunCI
